uv_tool_packages:
  - ansible-lint
  - ansible-dev-tools
  - beautysh
  - bump-my-version
  - compiledb
  - cython
  - git-filter-repo
  - ipython
  - marimo
  - mdformat
  - nbstripout
  - nox
  - pipdeptree
  - poetry
  - pre-commit
  - pudb
  - rstcheck
  - ruff
  - tox
  - ty@latest
  - twine
