- name: Tap mongodb tap
  community.general.homebrew_tap:
    name: mongodb/brew
- name: Install mac devtools
  community.general.homebrew:
    name:
      - aider
      - awscli
      - bats
      - btop
      - cargo-nextest
      - chicken
      - codex
      - duckdb
      - eksctl
      - ffmpeg
      - gemini-cli
      - gitlab-ci-local
      - google-cloud-sdk
      - guile
      - helmfile
      - htop
      - httpie
      - kind
      - kubecolor
      - llama.cpp
      - libomp
      - opam
      - opentofu
      - protobuf
      - ruby-build
      - rustup
      - sbcl
      - tofu-ls
      - zoxide
    state: present
    update_homebrew: true
