- name: Install homebrew casks
  community.general.homebrew:
    name:
      - font-andale-mono
      - font-anonymous-pro
      - font-commit-mono
      - font-fira-code
      - font-fira-mono
      - font-hack
      - font-ibm-plex-mono
      - font-ibm-plex-sans
      - font-inconsolata
      - font-jetbrains-maple-mono
      - font-jetbrains-mono
      - font-maple-mono
      - font-monaspace
      - font-new-computer-modern
      - font-roboto-mono
      - font-source-code-pro
      - font-symbols-only-nerd-font
      - font-victor-mono
