- name: Install devtools casks
  community.general.homebrew_cask:
    name:
      - claude
      - claude-code
      - docker-desktop
      - jordanbaird-ice
      - miniconda
      - ollama
      - openlens
      - vivaldi
      - zen
    state: present
