- name: Install devtools casks
  community.general.homebrew_cask:
    name:
      - claude
      - claude-code
      - docker-desktop
      - opencode-desktop
      - ollama
      - openlens
      - zen
    state: present
