- name: Install brew mac apps
  community.general.homebrew:
    name:
      - alt-tab
      - audacity
      - bartender
      # - drawio
      - easy-move-plus-resize
      - hammerspoon
      - insomnia
      - karabiner-elements
      - maccy
      - rectangle
      - spotify
      - vlc
      - wireshark
    state: present
    update_homebrew: true
